username: 在这里输入学号
password: 在这里输入密码
user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
url_login: https://idcheck2.qmul.ac.uk/idcheck
url_target: 你要上的课程页面